version: "3"
services:
  api-service:
    build: ./api
    command: npm run dev
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3350:3350
    depends_on:
      - db
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PORT: 3350
      HOST: 0.0.0.0
      NODE_ENV: development
      APP_KEY: 3vlNXXhbckXg3VYhb1G8KLRaL0xvbPUF
      CACHE_VIEWS: "false"
      DRIVE_DISK: local
      DB_CONNECTION: pg
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: adonis
      PG_PASSWORD: adonis
      PG_DB_NAME: adonis
      CM_COMPANY_ID: 6f71df6d-40bb-4027-a53d-e11396714bf9
      GUARDIAN_SERVICE_URL: http://host.docker.internal:3000/api/v1
      GUARDIAN_ROOT_USER: guardiandatasker
      HEDERA_OPERATOR_ID: 0.0.26558164
      HASHGRAPH_TRANSACTION_URL: https://testnet.dragonglass.me/hedera/transactions
      GUARDIAN_IMPORT_MESSAGE_ID: 1650504125.135379000
      DO_SPACES_ENDPOINT: sgp1.digitaloceanspaces.com
      DO_SPACES_NAME: datasker-file-uploads
      CM_USER_PASSWORD: UNIQUE_VALUE_1
      GUARDIAN_USER_PASSWORD: UNIQUE_VALUE_2
      GUARDIAN_ROOT_PASSWORD: UNIQUE_VALUE_3
      TOKEN_SECRET: UNIQUE_VALUE_4
      REFRESH_TOKEN_SECRET: UNIQUE_VALUE_5
      DO_SPACES_KEY: <DO_SPACES_KEY>
      DO_SPACES_SECRET: <DO_SPACES_SECRET>
      HEDERA_OPERATOR_KEY: <HEDERA_OPERATOR_KEY>
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: adonis
  frontend-service:
    stdin_open: true
    build: ./frontend
    links:
      - api-service
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3500:3500
    depends_on:
      - db
      - api-service
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PORT: 3500
      REACT_APP_API_HOST: http://localhost:3350
